name = "CGT"
uuid = "045abbb4-f877-49bb-b163-313f771439d9"
authors = ["Vlad Hanciuta <wladsh@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
